baseImageOverrides:
  dialo.ai/ipman/cmd/vxlandlord: ablmnzde/ipman-iproute2:0.1.19-abl2
  dialo.ai/ipman/cmd/restctl: ablmnzde/ipman-swanctl:0.1.19-abl2
  dialo.ai/ipman/cmd/xfrminjector: gcr.io/distroless/static
  dialo.ai/ipman/cmd/xfrminion: ablmnzde/ipman-iproute2:0.1.19-abl2
defaultPlatforms:
  - linux/amd64
  - linux/arm64
