baseImageOverrides:
  ./cmd/vxlandlord: ablmnzde/ipman-iproute2:0.1.19-abl1
  ./cmd/restctl: ablmnzde/ipman-swanctl:0.1.19-abl1
  ./cmd/xfrminjector: gcr.io/distroless/static
  ./cmd/xfrminion: ablmnzde/ipman-iproute2:0.1.19-abl1
defaultPlatforms:
  - linux/amd64
  - linux/arm64
