# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
  monitoring:
    enabled: false
    interval: 10s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "ghcr.io/dialohq/ipman/operator@sha256:7f6154c345270782ae51a65625fddb141ecbafbb81f04f699e8dea8c5a181afb"
  pullPolicy: IfNotPresent
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
  pullPolicy: "IfNotPresent"
# Restctl service configuration
restctl:
  image: "ghcr.io/dialohq/ipman/restctl@sha256:b10add9cb296bda87083a6b021da996b9241a39cbc22514e477c31d4fb9eaa49"
  pullPolicy: "IfNotPresent"
# Xfrminjector configuration
xfrminjector:
  image: "ghcr.io/dialohq/ipman/xfrminjector@sha256:baa6a8623a7140266504550115ce0f50a35c719645b19d730fbf22bdbb868f92"
  pullPolicy: "IfNotPresent"
  ttlSeconds: 120
# VxlanLord configuration
vxlandlord:
  image: "ghcr.io/dialohq/ipman/vxlandlord@sha256:e4e23eb711d5fda5a99561218c2d2b821f5e52f19c4aaea8b0cf0d56a6f3addb"
  pullPolicy: "IfNotPresent"
# XfrmMinion configuration
xfrminion:
  image: "ghcr.io/dialohq/ipman/xfrminion@sha256:d7b86fc2e1dc1347a790fd677a56f46cafc3597d74410a70190881633caf609f"
  pullPolicy: "IfNotPresent"
# Charon daemon configuration
charon:
  image: "plan9better/charon:0.1.17"
  pullPolicy: "IfNotPresent"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}

---
