# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
  monitoring:
    enabled: false
    interval: 10s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "ghcr.io/dialohq/ipman/operator@sha256:3d182e579a1dc3531ff48dfb5996d6d46afbc8b45434f409620f0a76d9502775"
  pullPolicy: IfNotPresent
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
  pullPolicy: "IfNotPresent"
# Restctl service configuration
restctl:
  image: "ghcr.io/dialohq/ipman/restctl@sha256:bab3b409ce1e896273980a3e736a0a4f72f5d37131971b65fa8053823a7d902a"
  pullPolicy: "IfNotPresent"
# Xfrminjector configuration
xfrminjector:
  image: "ghcr.io/dialohq/ipman/xfrminjector@sha256:71f2991c5765c68e2faf79543bdf73f189c8d5eb231669e94572ae656d16b1d0"
  pullPolicy: "IfNotPresent"
  ttlSeconds: 120
# VxlanLord configuration
vxlandlord:
  image: "ghcr.io/dialohq/ipman/vxlandlord@sha256:adec1e3c072e098e8776fadc88dd20c378c56615a34e7bb06d12301f3896b928"
  pullPolicy: "IfNotPresent"
# XfrmMinion configuration
xfrminion:
  image: "ghcr.io/dialohq/ipman/xfrminion@sha256:dc4657dc5c4df60eac9ca8aa10fc11b7ec63355ba006d7a61b9eafca0341e48f"
  pullPolicy: "IfNotPresent"
# Charon daemon configuration
charon:
  image: "plan9better/charon:latest-dev"
  pullPolicy: "IfNotPresent"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}

---
