# Default values for ipman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "ipman-system"
  socketPath: "/var/run/ipman"
  monitoring:
    enabled: false
    interval: 10s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "ghcr.io/dialohq/ipman/operator@sha256:2b9a9d5c79f71db7f93fafb4e35d9f5cfedc29f6e20ad787bc5341aef6fec4dd"
  pullPolicy: IfNotPresent
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Caddy proxy configuration
caddy:
  image: "caddy:2.10.0-alpine"
  pullPolicy: "IfNotPresent"
# Restctl service configuration
restctl:
  image: "ghcr.io/dialohq/ipman/restctl@sha256:11e1bff800e3b6b8982c1de542a3e31bcec7a38ebe5badcfe895a727fa0155c1"
  pullPolicy: "IfNotPresent"
# Xfrminjector configuration
xfrminjector:
  image: "ghcr.io/dialohq/ipman/xfrminjector@sha256:308b1c5582c49556403ceabdb37fb6890f8eb057adc094871ef9e4d1ca07c825"
  pullPolicy: "IfNotPresent"
  ttlSeconds: 120
# VxlanLord configuration
vxlandlord:
  image: "ghcr.io/dialohq/ipman/vxlandlord@sha256:36756cdc0aa7ed84f80fe92cc116e93fc6a3971c7f7b3bc26b0cf6ebfd545636"
  pullPolicy: "IfNotPresent"
# XfrmMinion configuration
xfrminion:
  image: "ghcr.io/dialohq/ipman/xfrminion@sha256:5f051d61847732d5b427a8567f141a5916c2a2f95752d48adebec27bd65eead8"
  pullPolicy: "IfNotPresent"
# Charon daemon configuration
charon:
  image: "plan9better/charon:0.1.17"
  pullPolicy: "IfNotPresent"
# Webhook configuration
webhook:
  serviceName: "ipman-webhook-service"
  mutatingWebhookName: "ipman-mutating-webhook"
  validatingWebhookName: "ipman-validating-webhook"
  certificate:
    name: "ipman-webhook-certificate"
    secretName: "ipman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "ipman-cluster-resource-access"
  clusterRoleBindingName: "ipman-role-binding"
# Service account configuration
serviceAccount:
  annotations: {}
  name: "ipman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}

---
